name: audio_service_example
description: Demonstrates how to use the audio_service plugin.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.8.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.5.1
  just_audio: ^0.0.6
  flutter_tts: ^0.8.5
  rxdart: ^0.23.1
  audio_service:
    path: ../
  cupertino_icons: ^0.1.2

dev_dependencies:
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
